### ISSUE TITLE
Why is the secret_accessors_list not present in the official module documentation? Is it not exposed

### ISSUE THREAD

**Issue by mm-bala** [GoogleCloudPlatform/terraform-google-secret-manager#81]
I have a question:
Why do I not see secret_accessors_list in the below official terraform module?
https://registry.terraform.io/modules/GoogleCloudPlatform/secret-manager/google/0.2.0

Is it not exposed? But I see it in variables.tf though.

**Comment by legal90** [comment]
@mm-bala I'm not a module maintainer, but I think I can reply to that.
`secret_accessors_list` is not documented in the terraform registry because it is not available in the current latest version, v0.2.0. 
That variable was added after v0.2.0 release, by that PR: https://github.com/GoogleCloudPlatform/terraform-google-secret-manager/pull/66 and wasn't yet released.

It should be included into the upcoming v0.3.0 release: https://github.com/GoogleCloudPlatform/terraform-google-secret-manager/pull/65

**Comment by apeabody** [comment]
Correct, v0.3.0 with `secret_accessors_list` has now be released: https://registry.terraform.io/modules/GoogleCloudPlatform/secret-manager/google/0.3.0?tab=inputs
